### ISSUE TITLE
instructions for challenge 7 doesn't explain what is required from students

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/sql-commands-intro#10]
[In the solutions](https://github.com/foundersandcoders/sql-commands-intro/blob/2182ad3abfc6c933562cae69d35610a048f4240c/solutions.sql#L20-L24)
> SELECT id,
>       CASE WHEN age<20 THEN 'true'
>            ELSE 'false'
>       END AS teenager
>    FROM users;

but this is not obvious from the instructions
> Using CASE WHEN, get a list of user ids from the users table and label a new row, teenager with true or false.

It may seem obvious that they would need to write a query with `age<20`, but it would help to give real world context that explains _why_ students are writing the query. That would also help to contextualise why they need to return a new row with true/false boolean

**Comment by jsms90** [comment]
How about:
> You need to find out which of your users are teenagers and which are not. Once you have this information, your application needs to do something with the user's ID.
> Use `CASE WHEN` and `AS` to write a query which returns the id and a new row called "teenager", whose value can either be `true` or `false`.

?

**Comment by macintoshhelper** [comment]
Is this good?

>You need to find out which of your users are teenagers and which are not. Using [`CASE WHEN`](https://www.postgresql.org/docs/7.4/static/functions-conditional.html) and [`AS`](https://www.w3schools.com/sql/sql_alias.asp), show a list of users by their `id` and a new column called `teenager` with the values `true` or `false`.

**Comment by jsms90** [comment]
Better. But more real world context might be useful. Otherwise, it's hard to understand why you would need the teenager column, instead of just doing:
`SELECT id FROM users WHERE age<20`
and
`SELECT id FROM users WHERE age>=20`
