### ISSUE TITLE
Bonus question's test not testing everything

### ISSUE THREAD

**Issue by maxgerber** [foundersandcoders/sql-commands-intro#11]
The test code isn't testing every aspect of this challenge. Instead the test statement could be:
``` SELECT text_content FROM post_comments WHERE id = 2 AND post_id = 2 ```

**Comment by macintoshhelper** [comment]
Thanks, I've replace `id` with `post_id`, incase someone has added multiple rows by accident, increasing the id count.

Does this solve the issue? Please close issue if so
https://github.com/foundersandcoders/sql-commands-intro/blob/workshop-fixes/README.md#using-insert-and-update

**Comment by maxgerber** [comment]
That's the ticket 👍
