### ISSUE TITLE
add real world context - set the scene before "schema diagrams" e.g. with a user persona

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/sql-commands-intro#12]
If you've never made a schema before, seeing a few tables at the top of the readme may not mean very much. Students need to be told what to do with this information, in order for it to be useful.

Personally, I just skipped over reading the schema diagrams and went straight to the challenges. I got to exercise 5 before I realised that there were more tables than `users`.

It would help to set the scene and relate this schema to the real world scenario in which we might use it. Then, when they come to the challenges, students are relating the commands like `WHERE` and `CASE WHEN`, etc to a real world scenario.

Making this connection whilst going through the workshop will mean that students can make these connetions immediately, when they go into projects. Otherwise (in my cohort, for example), students have to go back and look up every command again because they never learned the syntax in relation to why they want to use them and in what situation.

**Comment by macintoshhelper** [comment]
Does https://github.com/foundersandcoders/sql-commands-intro/blob/011b1cf78320f629d133b1dcd2885ae4c4d48f7c/README.md#schema-info address this?

**Comment by jsms90** [comment]
So speedy @macintoshhelper :heart: 

This is a start, but to be honest, I would still offer them even more of an introduction. They've just heard an introduction to what database are and what a schema is. But this is the first time they've actually seen one written down and they've never designed one themselves. It would be really good to walk them through the thought process of creating one, based on a real world scenario.

It might help to think of this as if it were a real project being explained to you. Imagine you are a Product Owner who wants to hire more devs for their team. You need to introduce your product to these potential new devs. They have never seen your product before. They have no idea what it is or what it does. You want to reduce the cognitive overhead as much as possible, so that when they see the database schema, it already makes perfect sense to them and they don't need to spend time trying to figure out how it all relates.

As a PO, you need to
1. Set the scene by giving them context - what problem are you trying to solve by creating your site? Remember: the devs are coming in cold and probably context switching from something else in their lives (just as true of the students sitting down to do the workshop).
1. Where are you at in your project? (Just made `init.sql`, so you're only just starting. You're making your database from scratch and you've got some data you want to populate it with.)
1. Explain the database schema - i.e. the tables that already exist. It helps to put this into context, by referring back to the problem you're trying to solve.
1. Tell the devs what you want them to do with the existing data.
