### ISSUE TITLE
Setting up the workshop database instructions

### ISSUE THREAD

**Issue by ghost** [foundersandcoders/sql-commands-intro#2]
We should make it clear what these commands are doing rather than telling them to blindly follow:
`\c blog_workshop
\i init.sql`

**Comment by jsms90** [comment]
Might be nice to have something more verbose like this https://github.com/foundersandcoders/postgres-workshop#psql

**Comment by sbinlondon** [comment]
@ConchobarMacNessa @macintoshhelper Has this issue been resolved?
