### ISSUE TITLE
Update expected result for 5

### ISSUE THREAD

**Issue by ghost** [foundersandcoders/sql-commands-intro#3]
at the moment, we have the expected result showing the user_id, but the id is just stored as id in the table. Unless we're asking them specifically to save it as user_id, we should just keep this as id.

**Comment by macintoshhelper** [comment]
Thanks for spotting the mistake, I meant to use id, I've fixed this in b00f567

**Comment by macintoshhelper** [comment]
Oh, just realised I think it should actually be `user_id`, since it's a foreign key. I'll change it back, but have made it clearer that it's user who has posted a blog post.

**Comment by sbinlondon** [comment]
@ConchobarMacNessa @macintoshhelper Can I close this issue or has it not been resolved?
