### ISSUE TITLE
students need to be taught SQL syntax before they can complete this workshop

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/sql-commands-intro#4]
It's a bit misleading to point them to a workshop that they can't complete without first being taught SQL commands.

It was my understanding that you were creating a workshop to replace www.pgexercises.com, which would actually teach students to use SQL syntax? If they're required to read [`learn-sql`](https://github.com/macintoshhelper/learn-sql/tree/master/postgresql) before they are able to complete this workshop, then why not just put the contents of `learn-sql` into this workshop?

**Comment by jsms90** [comment]
Or perhaps getting them to read `learn-sql` first isn't necessary at all.

The problem is that the "Hints" at the bottom aren't really "hints" if the students have never used the syntax before. These are things that just need to be taught.

Right now we have:
> 1. Retrieve all the information from the users table

If you want to teach them to google everything, you could put a line at the top stating that students are expected to google each of the commands they find below.

Then change the instruction to specify which command they need:
> 1. Use `SELECT` to retrieve all the information from the users table

Or, if you don't think that telling them to google "SELECT" is that useful, you could link them directly to a useful article, within the instructions:
> 1. Use [`SELECT`](https://www.w3schools.com/sql/sql_select.asp) to retrieve all the information from the users table

@ConchobarMacNessa @pbywater what do you think?

**Comment by macintoshhelper** [comment]
Ok, I'll do that, that sounds good.

**Comment by macintoshhelper** [comment]
I've done this in c9f361f
