### ISSUE TITLE
clarify what needs to be selected for challenge 3

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/sql-commands-intro#8]
> Using SELECT and WHERE, retrieve a list of users who are older than 50

"a list of users" could be interpreted as just the usernames i.e. `SELECT username FROM users WHERE age>50;` rather than `SELECT * FROM...`

The "expected result" makes it pretty obvious. But it might help to make the instruction really explicit too.

**Comment by sbinlondon** [comment]
@macintoshhelper @jsms90 Can this be closed, as it appears to have been solved?
